env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  # `var`を使ったら怒るよ
  no-var: error

  # セミコロン抜かないで
  semi: error

  # `==` とかを使わないでね
  eqeqeq: error

  # カンマのあとはスペースを入れてくれ
  comma-spacing: error

  # 式代入の前後はスペース入れてね
  react/jsx-curly-spacing:
    - error
    - when: always
      children: true

  # インデントは2で守ってね
  indent:
    - error
    - 2

  # `console.log`は消しておいて
  no-console: error

  # ブロック演算子はスペース入れてね
  block-spacing: error

  # 演算子の前後のスペースは絶対抜かないで
  space-infix-ops: error

  # アロー演算子前後のスペース強制
  arrow-spacing: error

  # タブとスペースを混ぜないで
  no-mixed-spaces-and-tabs: error

  # 全角スペースは許容
  no-irregular-whitespace: off
